# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html
* Уэс Маккини. Python и анализ данных

## Задачи для совместного разбора

In [2]:
import numpy as np
lst=[1,2,3,4,6,7,9]
lst
[i**2 for i in lst]


[1, 4, 9, 16, 36, 49, 81]

In [3]:
arr= np.array(lst)
arr**2

array([ 1,  4,  9, 16, 36, 49, 81])

In [4]:
mask = arr < 4
mask

array([ True,  True,  True, False, False, False, False])

In [5]:
arr[mask]

array([1, 2, 3])

In [6]:
arr= np.arange(20).reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
arr[:3,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [11]:
import pandas as pd

file=np.loadtxt("/content/minutes_n_ingredients.csv",dtype='int32', skiprows=1, delimiter="," )
print (file[:5])




[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]] 300000


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [66]:
maax=np.max(file,axis=0 )[:2]
print (maax, "max")
miin=(np.min(file,axis=0))[:2]
print (miin, "min")
avvr=np.average(file,axis=0)[:2] #mean
print (avvr,"average")
medd=np.median(file,axis=0)[:2]
print (medd,"median")

537671 max
[38  0] min
[222064.32391  21601.00169] average
[2.071935e+05 4.000000e+01] median


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [71]:
copy = file[:,1:3]
#print (copy[:,1:2])
kvant=np.quantile(copy[:,1:2],0.75)
#print (copy[:,0:1])
print (kvant," Квантиль\n")

if (maax[1]>9):
  maax[1]=9
print (maax)

if (miin[1]>9):
  miin[1]=9
print (miin)
if (avvr[1]>9):
  avvr[1]=9.0
print (avvr)
if (medd[1]>9):
  medd[1]=9.0
print (medd)

11.0  Квантиль

[537671      9]
[38  0]
[2.22064324e+05 9.00000000e+00]
[2.071935e+05 9.000000e+00]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [24]:
file[file==0]=1
print (file[:20])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]
 [152828     40      7]
 [ 33941     18      9]
 [446597     15      5]
 [366174      7      9]
 [ 74205     20      7]
 [504666     65     20]
 [ 81006     12      7]
 [280968     85     11]
 [204134      5      3]
 [ 18593     35      7]
 [ 25623      6      4]
 [ 65559     24     14]
 [ 99836    180      7]
 [ 87775     80     13]
 [425704     40     12]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [10]:
(uniq, freq)=np.unique(file, return_counts=True)
print (uniq.size , "уникальные значения")

100545


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [33]:
dictat=dict(zip(uniq, freq))
print (dictat)

{0: 479, 1: 250, 2: 1738, 3: 3358, 4: 5783, 5: 11997, 6: 9723, 7: 11035, 8: 11327, 9: 10700, 10: 14469, 11: 8518, 12: 7062, 13: 5392, 14: 3808, 15: 7859, 16: 2036, 17: 1725, 18: 1222, 19: 694, 20: 6777, 21: 419, 22: 756, 23: 511, 24: 200, 25: 5691, 26: 207, 27: 477, 28: 335, 29: 88, 30: 7970, 31: 117, 32: 351, 33: 241, 34: 80, 35: 5375, 36: 75, 37: 185, 38: 177, 39: 49, 40: 6093, 41: 50, 42: 179, 43: 80, 44: 44, 45: 4957, 46: 55, 47: 74, 48: 102, 49: 20, 50: 4266, 51: 30, 52: 60, 53: 65, 54: 18, 55: 3040, 56: 22, 57: 65, 58: 31, 59: 13, 60: 4464, 61: 25, 62: 41, 63: 39, 64: 24, 65: 2355, 66: 16, 67: 36, 68: 32, 69: 4, 70: 2648, 71: 7, 72: 51, 73: 12, 74: 15, 75: 2711, 76: 11, 77: 7, 78: 19, 79: 11, 80: 1886, 81: 11, 82: 15, 83: 10, 84: 15, 85: 760, 86: 6, 87: 14, 88: 11, 89: 9, 90: 1746, 91: 6, 92: 6, 93: 8, 94: 7, 95: 523, 96: 11, 97: 11, 98: 8, 99: 9, 100: 605, 101: 4, 102: 13, 103: 1, 104: 5, 105: 716, 106: 1, 107: 7, 108: 3, 109: 5, 110: 446, 111: 3, 112: 8, 114: 3, 115: 169, 116: 

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [40]:
copy = np.copy(file)
#print (copy[:20])
#print ([copy[:, 2] >5]) copy[:,[2] ]
cop = ([copy[:, 2] >5])
print (copy[cop])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [287943     85     15]
 [498432     65     15]
 [ 81993    140     14]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [45]:
print (uniq)
for i in file:
  print (i[0],i[2]/i[1])

Выходные данные были обрезаны до нескольких последних строк (5000).
418792 0.2857142857142857
64804 0.004137931034482759
91292 0.2
436847 0.009523809523809525
37816 0.4666666666666667
504874 0.35
120610 0.16
35951 0.6111111111111112
115822 0.26666666666666666
29351 0.36666666666666664
188384 0.15
359405 0.26666666666666666
9954 0.016304347826086956
309894 0.5
297857 0.25
36757 0.2857142857142857
85801 0.3333333333333333
104312 0.25
231826 0.5
196486 0.25
72185 0.4
23766 0.35
136552 0.08571428571428572
67473 0.15555555555555556
473901 0.2857142857142857
213715 0.2857142857142857
493438 0.8
40021 0.2
205731 0.1
94531 0.2
330327 1.25
474029 0.8571428571428571
156617 0.4666666666666667
434916 0.45
134082 0.34285714285714286
214707 0.625
264452 2.5
372919 0.32
254498 0.13333333333333333
343192 0.5555555555555556
293427 0.5333333333333333
145655 0.8
423941 0.40625
469819 0.057971014492753624
60024 0.004810996563573883
448124 0.010101010101010102
258383 0.26666666666666666
152379 0.12
53532 0

KeyboardInterrupt: ignored

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [50]:
print (file[file[:,1].argsort()][:100])

[[  4896      1     14]
 [  6975      1      8]
 [  3492      1      7]
 [  6577      1      7]
 [  2770      1      4]
 [  8097      1     17]
 [  3592      1     10]
 [  1399      1     10]
 [  2126      1     17]
 [  3324      1     10]
 [  3037      1     16]
 [  7351      1      9]
 [  6572      1     11]
 [454978      1      4]
 [314099      1      2]
 [  7183      1      9]
 [223912      1      7]
 [ 45675      1      4]
 [   736      1     11]
 [  4924      1      6]
 [181666      1      3]
 [  5012      1      7]
 [ 47760      1      7]
 [  4992      1      9]
 [ 99141      1      4]
 [  5115      1      6]
 [397572      1      3]
 [  3263      1      8]
 [  2726      1      9]
 [  4667      1      5]
 [  7015      1      8]
 [  7786      1      9]
 [  2425      1      7]
 [243814      1      3]
 [   902      1      7]
 [  4732      1      4]
 [ 80121      1      8]
 [  1527      1      9]
 [  7017      1     14]
 [  5354      1      8]
 [281119      1      4]
 [  4591      1 

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [57]:
random_row=file.shape[0]
random_rows=np.random.choice(random_row,size=10)
print (file[random_rows,:])


[[437616     30      8]
 [114839   1450      7]
 [128023     50      4]
 [ 34600      9      5]
 [480377     20     16]
 [219032     30     14]
 [247657     20     12]
 [ 58738     10      8]
 [178223      5      7]
 [224028     30     10]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [65]:
percentages = dict(zip(uniq, freq * 100 / len(file)))
#max(percentages, key=percentages.get)

max_value = min(percentages.values())  # maximum value
max_keys = [k for k, v in percentages.items() if v == max_value] # getting all keys containing the `maximum`

print(max_value,"проц соотношение")#, max_keys)

0.001 проц соотношение [103, 106, 116, 118, 119, 139, 146, 158, 159, 161, 171, 173, 174, 177, 178, 193, 198, 199, 203, 204, 206, 209, 214, 221, 224, 228, 231, 232, 238, 241, 251, 254, 257, 258, 262, 272, 276, 278, 279, 282, 284, 287, 291, 303, 304, 306, 316, 318, 319, 327, 329, 332, 351, 358, 361, 366, 369, 373, 384, 387, 393, 394, 396, 399, 409, 411, 421, 428, 437, 449, 454, 458, 459, 461, 466, 467, 472, 475, 478, 481, 484, 486, 487, 489, 494, 496, 497, 498, 502, 512, 514, 516, 519, 524, 526, 531, 533, 534, 536, 538, 543, 561, 563, 564, 567, 576, 579, 580, 593, 606, 607, 616, 623, 626, 632, 634, 636, 647, 648, 651, 657, 658, 669, 670, 671, 672, 674, 683, 685, 689, 696, 705, 707, 710, 719, 729, 736, 747, 754, 759, 768, 775, 779, 785, 795, 809, 820, 822, 830, 834, 843, 850, 856, 868, 876, 884, 885, 940, 964, 971, 974, 980, 989, 992, 1005, 1018, 1040, 1048, 1074, 1075, 1095, 1100, 1105, 1106, 1125, 1129, 1144, 1148, 1151, 1160, 1183, 1184, 1204, 1215, 1217, 1220, 1235, 1236, 1249, 1260, 

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [107]:
copy = np.copy(file)
a,b=file.shape
z=np.zeros((a,1), dtype=int)
copy=np.append(copy,z,axis=1)
for i in copy:
  if (i[1]<20 and i[2]<5):
    i[3]=1

print (copy)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [108]:

copy=copy[copy[:, 3].argsort()]
copy=copy[:,3]
unique, counts = np.unique(copy, return_counts=True)
print (unique,counts)
percentages = (copy/copy.sum(axis=0)*100)
print (percentages[-1],"\nanother method")
# maxx=counts[0]+counts[1]
# print (maxx)



[0 1] [94907  5093]
0.0196347928529354 
another method
100000


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.